@extends('website.layout')

@section('title', 'Shortlisted Hoardings')

@section('content')
    {{-- ================= SHARED SHORTLIST =================
         The client's view of a link generated by the team. There is no filter
         form here and no route into the wider inventory: the controller can
         only ever hand this page the ids stored against the token. --}}

    <div class="container-fluid about-banner-img g-0">
        <div class="row g-0">
            <div class="col-md-12 d-none d-md-block">
                <img src="{{ asset('assets/img/media_desk.png') }}" alt="Brand Adda" class="img-fluid w-100">
            </div>
            <div class="col-md-12 d-block d-md-none">
                <img src="{{ asset('assets/img/media_mobile.png') }}" alt="Brand Adda" class="img-fluid w-100">
            </div>
        </div>
    </div>

    <div class="container-fluid shared-head">
        <div class="container">
            <span class="bi-eyebrow">Shortlisted for you</span>
            <h1>{{ $link->title ?: 'Your Hoarding Shortlist' }}</h1>
            <p>
                Our team has picked
                <strong>{{ $mediaList->count() }}</strong>
                {{ Str::plural('hoarding', $mediaList->count()) }} for your requirement.
                Review them below, add the ones you want to your cart, and create a
                campaign or book online.
            </p>
        </div>
    </div>

    @if ($mediaList->count())
        <div class="container-fluid mt-4 mb-5">
            <div class="row">

                {{-- LEFT: the shortlisted cards, in the same format as search --}}
                <div class="col-lg-6 col-md-6 col-sm-12 shared-list">
                    <div class="row">
                        @include('website.media-home-list', ['mediaList' => $mediaList])
                    </div>
                </div>

                {{-- RIGHT: the same hoardings on the map --}}
                <div class="col-lg-6 col-md-6 col-sm-12">
                    <div id="sharedMap"></div>
                </div>

            </div>
        </div>
    @else
        {{-- Every hoarding on this link has since been removed from the
             inventory, so the link resolves but has nothing to show. --}}
        <div class="container-fluid mt-4 mb-5">
            <div class="bi-media-empty">
                <i class="bi bi-collection" aria-hidden="true"></i>
                <h4>These hoardings are no longer available</h4>
                <p>
                    The media on this shortlist has been taken off the platform.
                    Please contact our team and we will send you a fresh selection.
                </p>
            </div>
        </div>
    @endif
@endsection

@section('scripts')
    <link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>

    <script>
        (function () {
            const points = @json($mapMedia);
            const el = document.getElementById('sharedMap');
            if (!el || !points.length) return;

            const map = L.map('sharedMap').setView([20.5937, 78.9629], 5);

            L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                attribution: '&copy; OpenStreetMap'
            }).addTo(map);

            const detailsBase = "{{ url('/media-details') }}";
            const imageBase = "{{ config('fileConstants.IMAGE_VIEW') }}";
            const bounds = [];

            points.forEach(function (m) {
                const lat = parseFloat(m.latitude);
                const lng = parseFloat(m.longitude);
                if (isNaN(lat) || isNaN(lng)) return;

                // Same fallback the result cards use: media_title is optional
                // outside Hoardings/Billboards, so the category stands in.
                const title = [m.media_title || m.category_name || '', m.area_name || '']
                    .filter(Boolean).join(' ');

                const price = '₹ ' + Number(m.price || 0).toLocaleString('en-IN');

                const popup =
                    '<div style="min-width:170px;font-family:Montserrat,sans-serif;">' +
                    (m.first_image
                        ? '<img src="' + imageBase + m.first_image +
                          '" style="width:100%;height:90px;object-fit:cover;border-radius:8px;margin-bottom:6px;">'
                        : '') +
                    '<div style="font-weight:700;font-size:12px;color:#0F172A;">' + title + '</div>' +
                    '<div style="font-size:12px;font-weight:700;color:#F97316;margin-top:2px;">' + price + '</div>' +
                    '<a href="' + detailsBase + '/' + btoa(m.id) +
                    '" style="display:block;margin-top:8px;padding:5px 0;background:#F97316;color:#FFFFFF;' +
                    'border-radius:20px;text-align:center;font-size:11px;font-weight:600;text-decoration:none;">' +
                    'View Details</a>' +
                    '</div>';

                L.marker([lat, lng]).addTo(map).bindPopup(popup);
                bounds.push([lat, lng]);
            });

            // Frame the shortlist rather than the country. A single pin would
            // zoom to street level on its own, so that case is capped.
            if (bounds.length === 1) {
                map.setView(bounds[0], 13);
            } else if (bounds.length > 1) {
                map.fitBounds(bounds, { padding: [40, 40] });
            }
        })();
    </script>
@endsection
